name: VersaJoin
version: '${project.version}'
main: dev.ayame.versajoin.VersaJoin
description: "${project.description}"
permissions:
  versajoin.admin:
    description: "Let's you reload the plugin"
    default: op
  versajoin.format.staff:
    description: "Permission for staff ranks"
    default: false
  versajoin.format.donator:
    description: "Permission for donator ranks"
    default: false
commands:
  versajoin:
    description: "Main command"